# Generated by Django 3.2.9 on 2022-02-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=2000)),
                ('singer', models.CharField(max_length=2000)),
                ('tags', models.CharField(max_length=200)),
                ('album', models.CharField(default='', max_length=2000)),
                ('credit', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
